Template.home.helpers({
  welcome: function() {
    return 'Hello there, welcome to Meteor generated by Yeoman!';
  },
  additional: function() {
    return 'This is a very opinionated generator, future releases will include even more defaults.'
  }
});